### ISSUE TITLE
Failed to get transaction data

### ISSUE THREAD

**Issue by einsteinsfool** [luigi1111/xmr.llcoins.net#9]
Hello.

I wanted to learn how to use spend key with your project. I pasted txid, private spend key and my public address to your [checktx](http://xmr.llcoins.net/checktx.html) and I got this error:
"Failed to get transaction data! Perhaps MoneroBlocks is down?"

Tried both your online version and offline one downloaded from [here](https://github.com/luigi1111/xmr.llcoins.net/raw/master/site.zip).
MoneroBlocks is and wasn't down.

Any idea what might be the cause? I tried it without any proxy or VPN and I got txid, key and address from official Monero full node wallet v0.11.1.0.
Dunno what else I can tell you without my data.

**Comment by luigi1111** [comment]
Looks like MoneroBlocks has updated their API to HTTPS and didn't add my site for CORS to work. I've contacted the owner.

**Comment by luigi1111** [comment]
This has been resolved. Thanks for reporting.

**Comment by einsteinsfool** [comment]
Thanks. The online version works now.
But the problem is still the same with offline version. I guess everybody would need to be added by MoneroBlocks?
Or is there a way of checking the transaction on local machine, without your server?
